// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tutorial.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 会员赠送
type SendVip struct {
	SecretKey string `protobuf:"bytes,1,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	// 添加的会员时长
	MonthLength          int32      `protobuf:"varint,2,opt,name=month_length,json=monthLength,proto3" json:"month_length,omitempty"`
	UidArray             []string   `protobuf:"bytes,3,rep,name=uid_array,json=uidArray,proto3" json:"uid_array,omitempty"`
	Product              []*Product `protobuf:"bytes,4,rep,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SendVip) Reset()         { *m = SendVip{} }
func (m *SendVip) String() string { return proto.CompactTextString(m) }
func (*SendVip) ProtoMessage()    {}
func (*SendVip) Descriptor() ([]byte, []int) {
	return fileDescriptor_26b073342b6f55ff, []int{0}
}

func (m *SendVip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendVip.Unmarshal(m, b)
}
func (m *SendVip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendVip.Marshal(b, m, deterministic)
}
func (m *SendVip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendVip.Merge(m, src)
}
func (m *SendVip) XXX_Size() int {
	return xxx_messageInfo_SendVip.Size(m)
}
func (m *SendVip) XXX_DiscardUnknown() {
	xxx_messageInfo_SendVip.DiscardUnknown(m)
}

var xxx_messageInfo_SendVip proto.InternalMessageInfo

func (m *SendVip) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *SendVip) GetMonthLength() int32 {
	if m != nil {
		return m.MonthLength
	}
	return 0
}

func (m *SendVip) GetUidArray() []string {
	if m != nil {
		return m.UidArray
	}
	return nil
}

func (m *SendVip) GetProduct() []*Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                float32  `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	TitleType            int32    `protobuf:"varint,3,opt,name=title_type,json=titleType,proto3" json:"title_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_26b073342b6f55ff, []int{1}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetTitleType() int32 {
	if m != nil {
		return m.TitleType
	}
	return 0
}

func init() {
	proto.RegisterType((*SendVip)(nil), "main.SendVip")
	proto.RegisterType((*Product)(nil), "main.Product")
}

func init() { proto.RegisterFile("tutorial.proto", fileDescriptor_26b073342b6f55ff) }

var fileDescriptor_26b073342b6f55ff = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xcf, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x71, 0x25, 0x69, 0x09, 0xbe, 0x42, 0x07, 0x8b, 0xc1, 0x12, 0x42, 0x0a, 0x5d, 0xc8,
	0x94, 0x01, 0x9e, 0x80, 0x19, 0x84, 0x90, 0x41, 0xac, 0x51, 0x88, 0x4f, 0xf4, 0x44, 0x6a, 0x5b,
	0xe6, 0x3c, 0xf8, 0x31, 0x78, 0x63, 0x14, 0x27, 0x8c, 0xdf, 0xcf, 0x83, 0xff, 0x07, 0x7b, 0x8e,
	0xec, 0x02, 0x0d, 0x53, 0xe7, 0x83, 0x63, 0x27, 0x37, 0xa7, 0x81, 0xec, 0xe1, 0xb7, 0x80, 0xfa,
	0x0d, 0xad, 0xf9, 0x20, 0x2f, 0x6f, 0x00, 0x7e, 0x70, 0x0c, 0xc8, 0xfd, 0x37, 0x26, 0x55, 0x34,
	0x45, 0x2b, 0xb4, 0x58, 0xe4, 0x09, 0x93, 0xbc, 0x85, 0x8b, 0x93, 0xb3, 0x7c, 0xec, 0x27, 0xb4,
	0x5f, 0x7c, 0x54, 0x65, 0x53, 0xb4, 0x5b, 0xbd, 0xcb, 0xf6, 0x9c, 0x49, 0x5e, 0x83, 0x88, 0x64,
	0xfa, 0x21, 0x84, 0x21, 0xa9, 0xaa, 0xa9, 0x5a, 0xa1, 0xcf, 0x23, 0x99, 0xc7, 0x79, 0xcb, 0x3b,
	0xa8, 0x7d, 0x70, 0x26, 0x8e, 0xac, 0x36, 0x4d, 0xd5, 0xee, 0xee, 0x2f, 0xbb, 0x39, 0xa1, 0x7b,
	0x5d, 0x50, 0xff, 0xbf, 0x1e, 0x5e, 0xa0, 0x5e, 0x4d, 0xee, 0xa1, 0x24, 0xb3, 0xa6, 0x94, 0x64,
	0xe4, 0x15, 0x6c, 0x7d, 0xa0, 0x11, 0xf3, 0xe7, 0xa5, 0x5e, 0xc6, 0x1c, 0xce, 0xc4, 0x13, 0xf6,
	0x9c, 0x3c, 0xaa, 0x2a, 0x77, 0x89, 0x2c, 0xef, 0xc9, 0xe3, 0xe7, 0x59, 0x3e, 0xf8, 0xe1, 0x2f,
	0x00, 0x00, 0xff, 0xff, 0xf7, 0xdb, 0x1a, 0xa3, 0x02, 0x01, 0x00, 0x00,
}
